#! /bin/bash

[ -v CONTENT_LENGTH ] && read -N $CONTENT_LENGTH message_body
echo "set do:task:$message_body:completed `date '+%Y/%m/%d'`" | redis-cli > /dev/null
echo 'HTTP/1.1 201 Created'
echo 'Content-Type: text/plain'
echo ''
