#! /bin/bash

[ -v CONTENT_LENGTH ] && read -N $CONTENT_LENGTH message_body
echo 'HTTP/1.1 201 Created'
echo 'Refresh: 0;URL=/do/list.haml'
echo ''
while IFS='=' read -d '&' name value
do
	if [[ $name == id ]]
	then
		id="$value"
		for field in `cat /srv/tiva/static/do/create.haml.html | sed --silent "s/^.*<input name='\(.*\)' type='checkbox'>/\1/p"`
		do
			echo "del do:task:$id:$field" | redis-cli > /dev/null
		done
	fi
	[ -v id ] && echo "set do:task:$id:$name \"`urlencode -d $value`\"" | redis-cli > /dev/null
done <<< "$message_body&"
