#! /bin/bash

[ -v CONTENT_LENGTH ] && read -N $CONTENT_LENGTH message_body
echo 'HTTP/1.1 201 Created'
echo 'Content-Type: text/plain'
echo ''
echo "keys do:task:$message_body:*" | redis-cli | xargs echo 'del' | redis-cli > /dev/null
