#! /bin/bash

[ -v CONTENT_LENGTH ] && read -N $CONTENT_LENGTH message_body
echo "del do:task:$message_body:completed" | redis-cli > /dev/null
echo 'HTTP/1.1 201 Created'
echo 'Content-Type: text/plain'
echo ''
